#Spring Datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz_demo?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345

#Quartz Properties
  quartz:
    job-store-type: jdbc
    properties:
      org.quartz.threadPool.threadCount: 5

#Mail Properties
  mail:
    host: smpt.gmail.com
    port: 587
    username: elxan310@gmail.com
    password:
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true